default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_app_development
  username: postgres
  password: tshepi14c

test:
  <<: *default
  database: recipe_app_test
  username: postgres
  password: tshepi14c

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

